In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
chunk = pd.read_csv("NetBIOS.csv",dtype={'Flow Bytes/s': str}, low_memory=False, chunksize=50000)
df = pd.concat(chunk)

In [3]:
df_backup = df[:]

In [4]:
df.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,302291,172.16.0.5-192.168.50.4-648-16174-17,172.16.0.5,648,192.168.50.4,16174,17,2018-11-03 10:01:48.920574,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
1,341625,172.16.0.5-192.168.50.4-861-34200-17,172.16.0.5,861,192.168.50.4,34200,17,2018-11-03 10:01:48.920625,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
2,245313,172.16.0.5-192.168.50.4-862-4750-17,172.16.0.5,862,192.168.50.4,4750,17,2018-11-03 10:01:48.920685,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
3,266106,172.16.0.5-192.168.50.4-863-4443-17,172.16.0.5,863,192.168.50.4,4443,17,2018-11-03 10:01:48.921008,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
4,47182,172.16.0.5-192.168.50.4-864-48627-17,172.16.0.5,864,192.168.50.4,48627,17,2018-11-03 10:01:48.921010,48,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS

In [5]:
# Basic info
print(df.shape)
print(df.columns)
df.head()

(3455899, 88)
Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,302291,172.16.0.5-192.168.50.4-648-16174-17,172.16.0.5,648,192.168.50.4,16174,17,2018-11-03 10:01:48.920574,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
1,341625,172.16.0.5-192.168.50.4-861-34200-17,172.16.0.5,861,192.168.50.4,34200,17,2018-11-03 10:01:48.920625,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
2,245313,172.16.0.5-192.168.50.4-862-4750-17,172.16.0.5,862,192.168.50.4,4750,17,2018-11-03 10:01:48.920685,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
3,266106,172.16.0.5-192.168.50.4-863-4443-17,172.16.0.5,863,192.168.50.4,4443,17,2018-11-03 10:01:48.921008,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
4,47182,172.16.0.5-192.168.50.4-864-48627-17,172.16.0.5,864,192.168.50.4,48627,17,2018-11-03 10:01:48.921010,48,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS

In [8]:
df = df.drop(['Unnamed: 0', 'Flow ID',' Source IP', ' Destination IP', ' Timestamp'], axis=1)

In [9]:
# Clean column names first
df.columns = df.columns.str.strip()
df.replace('Infinity', np.nan, inplace=True)
# Convert problematic columns to numeric
df['Flow Bytes/s'] = pd.to_numeric(df['Flow Bytes/s'], errors='coerce')
df['Flow Packets/s'] = pd.to_numeric(df['Flow Packets/s'], errors='coerce')

# Drop rows with NaNs in these columns (optional, or you can fill them)
df.dropna(subset=['Flow Bytes/s', 'Flow Packets/s'], inplace=True)

# Confirm cleanup
print(df[['Flow Bytes/s', 'Flow Packets/s']].dtypes)

Flow Bytes/s      float64
Flow Packets/s    float64
dtype: object

In [12]:
df[['Flow Bytes/s', 'Flow Packets/s']].sample(20)

         Flow Bytes/s  Flow Packets/s
3181384  1.109804e+07    3.921569e+04
2913441  4.580000e+08    2.000000e+06
2737469  4.580000e+08    2.000000e+06
1252330  9.744681e+06    4.255319e+04
1106026  4.220000e+08    2.000000e+06
3071459  8.978723e+06    4.255319e+04
3257897  4.940000e+08    2.000000e+06
2605533  4.580000e+08    2.000000e+06
1255459  4.220000e+08    2.000000e+06
1902708  4.580000e+08    2.000000e+06
311263   4.580000e+08    2.000000e+06
162314   9.744681e+06    4.255319e+04
448777   4.580000e+08    2.000000e+06
2660344  4.580000e+08    2.000000e+06
459042   4.580000e+08    2.000000e+06
309744   8.980392e+06    3.921569e+04
2876153  9.541667e+06    4.166667e+04
2359554  4.220000e+08    2.000000e+06
2905904  4.580000e+08    2.000000e+06
204214   4.940000e+08    2.000000e+06

In [16]:
df[['Flow Bytes/s', 'Flow Packets/s']].sample(20)

         Flow Bytes/s  Flow Packets/s
1577460  2.290000e+08    1.000000e+06
2946119  4.580000e+08    2.000000e+06
2005081  9.541667e+06    4.166667e+04
1374139  4.220000e+08    2.000000e+06
1639631  4.580000e+08    2.000000e+06
2675774  6.020000e+08    2.000000e+06
2337084  2.290000e+08    1.000000e+06
1793293  8.833333e+06    4.166667e+04
1123966  2.290000e+08    1.000000e+06
946659   9.956522e+06    4.347826e+04
2033300  4.580000e+08    2.000000e+06
2692340  4.580000e+08    2.000000e+06
981237   1.017778e+07    4.444444e+04
2454299  4.580000e+08    2.000000e+06
2398440  4.580000e+08    2.000000e+06
217326   4.580000e+08    2.000000e+06
2942281  4.580000e+08    2.000000e+06
1121118  4.580000e+08    2.000000e+06
2762680  5.300000e+08    2.000000e+06
707614   4.580000e+08    2.000000e+06

In [ ]:
# Step 5: Drop rows with invalid/missing or very extreme values
df = df[df['Flow Bytes/s'] < 1e9]
df = df[df['Flow Packets/s'] < 1e7]
df.dropna(inplace=True)